### ISSUE TITLE
Behavior on failing function

### ISSUE THREAD

**Issue by nhard** [ohlmann/parallel_decorators#1]
Decorated function does not terminate correctly if it raises an error

Example

```python
from parallel_decorators import vectorize_parallel

@vectorize_parallel(method='processes',num_procs=2)
def foo(i):
    raise ValueError

foo(range(10))

```

**Comment by ohlmann** [comment]
Thanks for raising this issue.

It should be fixed in a83113433e98efcd1f08f8459e2a08d203573492
