### ISSUE TITLE
Scheduling: Dynamic vs Static

### ISSUE THREAD

**Issue by lczech** [ohlmann/parallel_decorators#5]
Would be nice to have a switch in `vectorize_parallel` for choosing the scheduling policy:

```
 @vectorize_parallel(method='processes', num_procs=2, scheduling='xyz')
```

where `xyz` is one of `auto` (current behaviour), `dynamic` (worker pool) or `static` (modulo).

**Comment by ohlmann** [comment]
When using processes, the scheduling is always dynamic. But this switch can be used for the MPI backend.

**Comment by ohlmann** [comment]
Done with 63a772964f3681b2c60e24485308822e6e0e4e2d.

**Comment by lczech** [comment]
Nice, that was fast! Thanks!
