### ISSUE TITLE
Invalid syntax `nonlocal`

### ISSUE THREAD

**Issue by lczech** [ohlmann/parallel_decorators#7]
When importing the file, I get

```
  File "deps/parallel_decorators/parallel_decorators.py", line 217
    nonlocal show_progressbar
                            ^
SyntaxError: invalid syntax
```

using Python 2.7.6. 

`nonlocal` seems to be a construct for Python >= 3, see https://stackoverflow.com/q/1261875/4184258

**Comment by ohlmann** [comment]
I changed the construct to work with python 2 as well as 3, fixed in 60a0c97a9e4d9bba2d923fdeb67d0320495b3d22.
