### ISSUE TITLE
Fatal error in  parallel_decorators.py / vectorize_mpi

### ISSUE THREAD

**Issue by jmoran2611** [ohlmann/parallel_decorators#9]
I could not get the decorator correctly working and after a lot of debugging i found the problem in this piece of code (lines 432 to 439 of parallel_decorators.py):

             for i in range(len(xs)):
                if rank == 0:
                    # root sends to all processes
                    for j in range(size):
                        comm.send(result[i], dest=j, tag=1)
                else:
                    # each process receives from root
                    result[i] = comm.recv(source=0, tag=1)

My code got stuck here as the first iteration of this loop consists of rank=0 sending the data to itself. As I didn't see any complain about this, I assume the behavior in this case may depend on the mpi version. For me, the code just stops there as the other ranks are waiting for data and rank 0 is waiting for itself to receive the data and that just does not happen. I made a quick fix by just changing the sending loop to:

             for i in range(len(xs)):
                if rank == 0:
                    # root sends to all processes
                    for j in range(size - 1):
                         j+=1
                        comm.send(result[i], dest=j, tag=1)
                else:
                    # each process receives from root
                    result[i] = comm.recv(source=0, tag=1)

But I am curious about why this problem didn't show up for anyone else

**Comment by ohlmann** [comment]
I am wondering about this as well.
I think all these lines should be replaced by a simple broadcast.
